####################################################################################
# 1) Builds the image once and tag it "airflow:celery"
####################################################################################

services:

  airflow-image:
    build: .
    image: airflow:celery
    pull_policy: never
    command: [ "/bin/true" ]

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: airflow
      RABBITMQ_DEFAULT_PASS: airflow
      RABBITMQ_PLUGINS: rabbitmq_stream
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
      - "5552:5552" # Stream protocol port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: airflow:celery
    env_file:
      - airflow.env
    depends_on:
      - postgres
      - rabbitmq
    command:
      - bash
      - -c
      - |
        uv run airflow db migrate &&
        uv run airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin

  scheduler:
    image: airflow:celery
    env_file:
      - airflow.env
    depends_on:
      - airflow-init
    command: [ "bash", "-c", "uv run airflow scheduler" ]

  webserver:
    image: airflow:celery
    env_file:
      - airflow.env
    depends_on:
      - scheduler
    ports:
      - "8000:8000"
    command: [ "bash", "-c", "uv run airflow webserver -p 8000 " ]

  flower:
    image: airflow:celery
    env_file:
      - airflow.env
    depends_on:
      - scheduler
    ports:
      - "5555:5555"
    command:
      - bash
      - -c
      - |
        uv run celery \
          --app airflow.executors.celery_executor.app \
          --broker "$$AIRFLOW__CELERY__BROKER_URL" \
          flower --port=5555
  worker1:
    image: airflow:celery
    env_file:
      - airflow.env
    depends_on:
      - scheduler
    command: [ "bash", "-c", "uv run airflow celery worker" ]

  worker2:
    image: airflow:celery
    env_file:
      - airflow.env
    depends_on:
      - scheduler
    command: [ "bash", "-c", "uv run airflow celery worker" ]

  worker3:
    image: airflow:celery
    env_file:
      - airflow.env
    depends_on:
      - scheduler
    command:
      - bash
      - -c
      - |
        uv run airflow celery worker -q high_priority

volumes:
  postgres_data:
  rabbitmq_data:
